mysite/hc_maquillaje/urls.py
from django.urls import path
from .views import crear_historia_clinica, HistoriaClinicaListView,HistoriaClinicaUpdateView,HistoriaClinicaDetailView

app_name = 'hc_maquillaje'  # Define el espacio de nombres aquí

urlpatterns = [
    path('crear/<int:paciente_id>/', crear_historia_clinica, name='crear_historia_clinica'),

    path('lista/<int:paciente_id>/', HistoriaClinicaListView.as_view(), name='historia_clinica_list'),

    path('editar/<int:pk>/', HistoriaClinicaUpdateView.as_view(), name='historia_clinica_edit'),  # Asegúrate de que esta línea esté presente

     path('historia/<int:pk>/', HistoriaClinicaDetailView.as_view(), name='ver_historia_clinica'),



]

mysite/login/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('protegida/', views.pagina_protegida, name='pagina_protegida'),
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),  # Asegúrate de que el nombre sea 'login'
    path('logout/', auth_views.LogoutView.as_view(next_page='homepage'), name='logout'),
     path('pacientes/', include('pacientes.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('login/', include('login.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('pacientes/', include('pacientes.urls')),
     path('hc_maquillaje/', include('hc_maquillaje.urls', namespace='hc_maquillaje')),
    
]

mysite/pacientes/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.listar_pacientes, name='listar_pacientes'),
    path('crear/', views.crear_paciente, name='crear_paciente'),
    path('<int:pk>/', views.detalle_paciente, name='detalle_paciente'),
    path('<int:pk>/editar/', views.editar_paciente, name='editar_paciente'),
    path('<int:pk>/eliminar/', views.eliminar_paciente, name='eliminar_paciente'),
    path('hc_maquillaje/', include('hc_maquillaje.urls')),
   
]

mysite/pacientes/models.py
from django.db import models

class Paciente(models.Model):
    nombre_completo = models.CharField(max_length=255)
    identificacion = models.CharField(max_length=50, unique=True)
    edad = models.IntegerField()
    genero = models.CharField(max_length=10, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')])
    telefono = models.CharField(max_length=20)
    direccion = models.CharField(max_length=255)
    correo_electronico = models.EmailField()
    ocupacion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_completo

class HistoriaClinica(models.Model):
    paciente = models.ForeignKey(
        Paciente, 
        on_delete=models.CASCADE,
        related_name='historias_clinicas_pacientes'
    )
    fecha = models.DateField()
    descripcion = models.TextField()

mysite/pacientes/forms.py
from django import forms
from .models import Paciente

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['nombre_completo', 'identificacion', 'edad', 'genero', 'telefono', 'direccion', 'correo_electronico', 'ocupacion']

mysite/pacientes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Paciente,HistoriaClinica
from .forms import PacienteForm

# Lista de pacientes
def listar_pacientes(request):
    search_query = request.GET.get('search', '')
    if search_query:
        pacientes = Paciente.objects.filter(identificacion__icontains=search_query)
    else:
        pacientes = Paciente.objects.all()
    return render(request, 'pacientes/listar_pacientes.html', {'pacientes': pacientes})

# Crear un paciente
def crear_paciente(request):
    if request.method == 'POST':
        form = PacienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_pacientes')  # Redirige a la página principal o donde desees
    else:
        form = PacienteForm()
    return render(request, 'pacientes/crear_paciente.html', {'form': form})

# Modificar un paciente
def editar_paciente(request, pk):
    paciente = get_object_or_404(Paciente, pk=pk)
    if request.method == 'POST':
        form = PacienteForm(request.POST, instance=paciente)
        if form.is_valid():
            form.save()
            return redirect('listar_pacientes')
    else:
        form = PacienteForm(instance=paciente)
    return render(request, 'pacientes/editar_paciente.html', {'form': form, 'paciente': paciente})
#ELIMINAR
def eliminar_paciente(request, pk):
    paciente = get_object_or_404(Paciente, pk=pk)
    if request.method == 'POST':
        paciente.delete()
        return redirect('listar_pacientes')
    return render(request, 'pacientes/eliminar_paciente.html', {'paciente': paciente})

#VER PACIENTE 
def detalle_paciente(request, pk):
    paciente = get_object_or_404(Paciente, pk=pk)
    historias_clinicas = HistoriaClinica.objects.filter(paciente=paciente)
    return render(request, 'pacientes/detalle_paciente.html',
                  {'paciente': paciente,
                   'historias_clinicas': historias_clinicas,
                    'crear_historia_clinica_url': reverse('hc_maquillaje:crear_historia_clinica', args=[paciente.id])})

mysite/pacientes/templates/pacientes/crear_paciente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Paciente</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load form_tags %}
</head>
<body>
    {% include 'pacientes/navbar.html' %}

    <div class="container mt-4">
        <h2 class="mb-4">Crear Paciente</h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="row mb-3">
                {% for field in form %}
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Guardar Paciente</button>
        </form>

        <!-- Botón para volver a la lista de pacientes -->
        <a href="{% url 'listar_pacientes' %}" class="btn btn-secondary mt-3">Volver a Pacientes</a>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9nF6el8gON7P0I4O4x02Ra6sF5c6TI5TITbE/BXxHbd8uW8Hc4Hk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-5pPp2k8S7Yb8uV8jODJXQ8G9v+y5lvZx8T3ITa5zlgj0k1Umh7aQoFSkKr5l5L7" crossorigin="anonymous"></script>
</body>
</html>

mysite/pacientes/templates/pacientes/detalle_paciente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles del Paciente</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'pacientes/navbar.html' %}

    <div class="container mt-4">
        <h1 class="mb-4">Detalles del Paciente</h1>

        <div class="card">
            <div class="card-header bg-primary text-white">
                <h5 class="card-title mb-0">{{ paciente.nombre_completo }}</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Identificación:</strong> {{ paciente.identificacion }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Edad:</strong> {{ paciente.edad }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Género:</strong> {{ paciente.genero }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Teléfono:</strong> {{ paciente.telefono }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Dirección:</strong> {{ paciente.direccion }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Correo:</strong> {{ paciente.correo_electronico }}</p>
                    </div>
                    <div class="col-md-3 mb-3">
                        <p class="card-text"><strong>Ocupación:</strong> {{ paciente.ocupacion }}</p>
                    </div>
                </div>
                <div class="d-flex justify-content-between mt-3">
                    <a href="{% url 'editar_paciente' paciente.pk %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'eliminar_paciente' paciente.pk %}" class="btn btn-danger">Eliminar</a>
                    <a href="{% url 'listar_pacientes' %}" class="btn btn-secondary">Volver a la lista</a>
                    <a href="{% url 'hc_maquillaje:crear_historia_clinica' paciente.id %}" class="btn btn-primary">Crear Historia Clínica</a>
                    <a href="{% url 'hc_maquillaje:historia_clinica_list' paciente.id %}" class="btn btn-primary">Ver Historias Clínicas</a>


                    


                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9nF6el8gON7P0I4O4x02Ra6sF5c6TI5TITbE/BXxHbd8uW8Hc4Hk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-5pPp2k8S7Yb8uV8jODJXQ8G9v+y5lvZx8T3ITa5zlgj0k1Umh7aQoFSkKr5l5L7" crossorigin="anonymous"></script>
</body>
</html>

mysite/pacientes/templates/pacientes/editar_paciente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Paciente</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load form_tags %}
</head>
<body>
    {% include 'pacientes/navbar.html' %}

    <div class="container mt-4">
        <h1 class="mb-4">Editar Paciente</h1>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="row mb-3">
                {% for field in form %}
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a href="{% url 'listar_pacientes' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9nF6el8gON7P0I4O4x02Ra6sF5c6TI5TITbE/BXxHbd8uW8Hc4Hk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-5pPp2k8S7Yb8uV8jODJXQ8G9v+y5lvZx8T3ITa5zlgj0k1Umh7aQoFSkKr5l5L7" crossorigin="anonymous"></script>
</body>
</html>

mysite/pacientes/templates/pacientes/eliminar_paciente.html
<!DOCTYPE html>
<html>
<head>
    <title>Eliminar Paciente</title>
</head>
<body>
    {% include 'pacientes/navbar.html' %}
    <h1>Eliminar Paciente</h1>
    <p>¿Estás seguro de que quieres eliminar a {{ paciente.nombre_completo }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'listar_pacientes' %}">Cancelar</a>
</body>
</html>

mysite/pacientes/templates/pacientes/listar_pacientes.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Pacientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'pacientes/navbar.html' %}

    <div class="container mt-4">
        <h1 class="mb-4">Lista de Pacientes</h1>

        <form method="get" action="{% url 'listar_pacientes' %}" class="mb-4">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Buscar por identificación" value="{{ request.GET.search }}">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </form>

        <ul class="list-group mb-4">
            {% for paciente in pacientes %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'detalle_paciente' paciente.pk %}" class="link-primary">{{ paciente.nombre_completo }}</a>
                    <div>
                      <!-- <a href="{% url 'hc_maquillaje:crear_historia_clinica' paciente.pk %}" class="btn btn-sm btn-success me-2">Crear Historia Clínica</a> -->  
                        <a href="{% url 'editar_paciente' paciente.pk %}" class="btn btn-sm btn-warning me-2">Editar</a>
                        <a href="{% url 'eliminar_paciente' paciente.pk %}" class="btn btn-sm btn-danger">Eliminar</a>
                    </div>
                </li>
            {% empty %}
                <li class="list-group-item">No se encontraron pacientes.</li>
            {% endfor %}
        </ul>

        <a href="{% url 'crear_paciente' %}" class="btn btn-success">Crear Nuevo Paciente</a>
        <a href="{% url 'listar_pacientes' %}" class="btn btn-secondary">Ver Todos los Pacientes</a>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9nF6el8gON7P0I4O4x02Ra6sF5c6TI5TITbE/BXxHbd8uW8Hc4Hk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-5pPp2k8S7Yb8uV8jODJXQ8G9v+y5lvZx8T3ITa5zlgj0k1Umh7aQoFSkKr5l5L7" crossorigin="anonymous"></script>
</body>
</html>

mysite/pacientes/templates/pacientes/navbar.html
<!-- pacientes/navbar.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'listar_pacientes' %}">Pacientes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">Bienvenido, {{ user.username }}</span>
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">Cerrar sesión</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>